### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by KeFeuer** [Aidiakapi/early_construction#17]
the mod loads in and the robots and the gear ist there but they dont do anything nether destroying nore building

**Comment by Aidiakapi** [comment]
Did you happen to have accidentally disabled personal logistics?
https://github.com/Aidiakapi/early_construction/issues/16

**Comment by KeFeuer** [comment]
how do i do that?

**Comment by KeFeuer** [comment]
ah im stupid just relized ty for help have a nice day
