### ISSUE TITLE
Early bots shadow "wobble" during working animation

### ISSUE THREAD

**Issue by millerlarson** [Aidiakapi/early_construction#3]
I noticed that early bots seem to suffer the same shadow "wobble" while working as with an old forum issue I happen to recall seeing: [[0.17.48] [Minor] Construction bot working animation's shadow is peculiar](https://forums.factorio.com/71909).

Especially noticable for longer animations, such as repairing or having them go to town on stumps when fiddling with [Terraforming](https://mods.factorio.com/mod/Shifting_Sands)

And thank you for this mod!  I just noticed today how slick the subtle tweaks to the base armor icons are; well done.

**Comment by Aidiakapi** [comment]
Thanks for the report! Did you ever figure out how to fix it for your own bots?

**Comment by millerlarson** [comment]
I fixed nothing.  I only remember seeing that forum topic before, which appears to be the same or similar issue.

Might be worth reaching out to posila or Deadlock.  No clue what the actual problem was.  A few frames from a spritesheet maybe?

**Comment by Aidiakapi** [comment]
Ah yeah, my bad, I somehow thought you originally reported the issue.

Oh well, I've reworked the prototypes and graphics, so it now matches the vanilla game again, as well as having the neat benefit of some of the visual improvements there have been since then.

**Comment by millerlarson** [comment]
> Ah yeah, my bad, I somehow thought you originally reported the issue.

Not a problem at all, haha.

> Oh well, _**I've reworked the prototypes and graphics**_, so it now matches the vanilla game again, as well as having the neat benefit of some of the visual improvements there have been since then.

Wow!  Awesome, thank you!
